#!/bin/sh

set -e

#Disable the network manager plugin backend service.
#NetworkManager will start service automatic.
if [ ! -e /var/cache/deepin/mark-setup-network-services ];then
    update-rc.d ipsec disable || true
    update-rc.d xl2tpd disable || true
    update-rc.d openvpn disable || true
    mkdir -p /var/cache/deepin
    touch /var/cache/deepin/mark-setup-network-services
fi

#DEBHELPER#

exit 0
